### PR TITLE
issue #14 interactive chat bot made for jwoc 

### PR DESCRIPTION
**Pull request by ronitblenz**
I used twilio to make this bot and I have mentioned all the env variables needed and presets for twilio account
Kindly merge the PR
Screenshot 2022-02-03 at 11 41 01 AM

Thanks and Regards

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
Hey @ronitblenz it's amazing , just to make sure the deployment of chat-bot is working well can you please run this in the website on your local system and send a short video on discord through personal dm.

**Comment by ronitblenz** [comment]
> Hey @ronitblenz it's amazing , just to make sure the deployment of chat-bot is working well can you please run this in the website on your local system and send a short video on discord through personal dm.
>  

Ok sure.... I need to set the environment... It will take time... Grant me few hours... I will dm you soon

**Comment by ronitblenz** [comment]
I have sent you the Demo, Please check it and merge my PR 😊

**Comment by The-Shivam-garg** [comment]
Thank you @ronitblenz  , for resolving out the issue. i have merged your code into the repository.

**Comment by ronitblenz** [comment]
Thanks alot, I am happy to contribute to this project

**Comment by The-Shivam-garg** [comment]
image
Hey @ronitblenz your code is having some deployment issue do check it out again. and deploy it on your GitHub repo , once it's start working let me know

**Comment by ronitblenz** [comment]
Can we have a call? Coz, I thing your environment is not set correctly and have you entered the credentials of your own twilio profile?

**Comment by The-Shivam-garg** [comment]
Oh ohk will do that. Just give me sometime i will notify you tomorrow.
Till then start working on other issue .

**Pull request merged**
