### PR TITLE
Added Email

### LINKED ISSUE #105: Enhancement : Add the Email in the footer section.
image

Hey contributor,
I want you to add the email ,down below in the HAVE A QUESTION ? section.

##Output Preview 
**Have a Question?**
-  Exist Somewhere in BHARAT, Earth
-  1234-567-891
-  info@BigB.com
-  bigbeduwebsite@gmail.com

### PR DESCRIPTION
**Pull request by Atif0604**
## 🛠️ Fixes Issue

Closes #105 

## 👨‍💻 Changes proposed

Add the Email in footer

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
Resolve the pr conflicts

**Comment by Atif0604** [comment]
> Resolve the pr conflicts

Ok

**Comment by Atif0604** [comment]
Hey @The-Shivam-garg Resolved

**Comment by The-Shivam-garg** [comment]
great ! merged your code

**Pull request merged**
