### PR TITLE
Create backend for join free online courses #25

### PR DESCRIPTION
**Pull request by barnik109**
Issue done.

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
can you please share the deploy website., For that you can use GitHub pages

**Comment by barnik109** [comment]
Okay sharing in few minutes.

**Comment by barnik109** [comment]
https://barnik109.github.io/BigB-E-learn-Websit-e/

**Comment by The-Shivam-garg** [comment]
Thanks @barnik109 for resolving the issue, I have merged your code

**Pull request merged**
