### PR TITLE
change some images and set content

### PR DESCRIPTION
**Pull request by nik132-eng**
#385  

Closes #

## 👨‍💻 Changes proposed

make some differences from previous version

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

image

image

image

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
hey @nik132-eng please resolve the bugs at many places the text is not readable make sure , you resolve the issue 
image

**Comment by nik132-eng** [comment]
ok sorry i will do it 👍

**Comment by nik132-eng** [comment]
@The-Shivam-garg please check out my work

**Comment by The-Shivam-garg** [comment]
> @The-Shivam-garg please check out my work

hey @nik132-eng please resolve the bugs at many places the text is not readable make sure you resolve all  the issues.
1.look the pre-text is not readable here
image
2.Text is not visible enough 
image

**Comment by nik132-eng** [comment]
ok sure

**Pull request closed without merging**
