### PR TITLE
Add more courses in course page #3

### PR DESCRIPTION
**Pull request by barnik109**
I have added courses in computer courses.

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
please show me the screenshot.

**Comment by barnik109** [comment]
Okay sending in few minutes.

**Comment by barnik109** [comment]
Screenshot (9)
Screenshot (10)

**Comment by The-Shivam-garg** [comment]
deploy the website on your forked repository and share the link

**Comment by barnik109** [comment]
It is showing failure when I deployed the site.

**Comment by barnik109** [comment]
https://barnik109.github.io/BigB-E-learn-Websit-e/Course/Courses.html

**Comment by The-Shivam-garg** [comment]
Thank you @barnik109 for resolving the issue. I have merged your code .

**Pull request merged**
