### PR TITLE
Implementation of the search button for courses

### PR DESCRIPTION
**Pull request by zugzwang03**
searchimplementation
Hey Shivam dada, I have successfully implemented the search button for the different courses available using html, CSS and javascript, however the styling part got distorted a bit in the process. I hope someone else having expertise in that field can mend it well.

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
hey @zugzwang03 you did a great job !, can you please deploy the website on your fork repo , so i can check it's functioning  manually .

**Comment by zugzwang03** [comment]
I have deployed the website on my forked repo. You can check its functioning manually by going there.

**Comment by The-Shivam-garg** [comment]
Sure

**Comment by zugzwang03** [comment]
I activated the github pages. Can you please check now? You can try from here also https://zugzwang03.github.io/BigB-E-learn-Websit-e/

**Comment by The-Shivam-garg** [comment]
Ohk great! @zugzwang03 , for resolving the issue. I have merged your code

**Pull request merged**
