### PR TITLE
Make UI beautiful of Website 

### PR DESCRIPTION
**Pull request by nik132-eng**
#385 

Closes #

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

image

image

image

### CODE REVIEW

**Comment by nik132-eng** [comment]
Did some mistake in committing code in the previous branch so make new PR. 

@The-Shivam-garg  please check it out and let me know If any changes require. 
thank you.

and sorry for your inconvenience.

**Comment by nik132-eng** [comment]
image
 
please add labels also

**Comment by nik132-eng** [comment]
@The-Shivam-garg  sir please check my code and if any update is required let me know.

**Comment by The-Shivam-garg** [comment]
hey please resolve the PR conflicts

**Review by sakshamgurbhele — APPROVED** [review]
LGTM

**Comment by sakshamgurbhele** [comment]
@nik132-eng please resolve conflicts

**Pull request closed without merging**
