### PR TITLE
Solved issue #227 . Changed the UI of header/navbar

### PR DESCRIPTION
**Pull request by Rishita489**
## 👨‍💻 Changes proposed

I have changed the UI of header (navbar) . I have also included Sign-In option in the navbar rather than having a separate button on each page . 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

image

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
hey @Rishita489 can you please change the color or make it relevant to the bg image color , as it seems a little odd

**Comment by Rishita489** [comment]
> hey @Rishita489 can you please change the color or make it relevant to the bg image color , as it seems a little odd

Which element color needs to be changed ?

**Comment by The-Shivam-garg** [comment]
the entire navbar 

> > hey @Rishita489 can you please change the color or make it relevant to the bg image color , as it seems a little odd
> 
> Which element color needs to be changed ?

the entire navbar color ,or make it similar like the other navbars in blog page

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , I have changed the hover-color . I will send another PR . You please review and merge it .

**Comment by Rishita489** [comment]
Ok I will change the color and send the PR .

**Pull request closed without merging**
