### PR TITLE
links of courses added

### LINKED ISSUE #242: [FEATURE] Adding link to the Courses
### Description

Hey Contributor!
we want you to make each of these Block connect with the course page and its required course.

### Screenshots

image

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #242 

## 👨‍💻 Changes proposed
Created html files in /course/subjects of each respective course and linked them with courses of feature page.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Siddhesh777** [comment]
hey @The-Shivam-garg 
Please review this PR

**Review by sakshamgurbhele — APPROVED** [review]
LGTM

**Comment by sakshamgurbhele** [comment]
@The-Shivam-garg can you please confirm the file structure,

**Comment by The-Shivam-garg** [comment]
seems! good enough @Siddhesh777 your code is merged

**Pull request merged**
