### PR TITLE
Counselling page fixes

### LINKED ISSUE #267: [FEATURE] Design a UI for Counselling Page
### Description

try to make something eye catching 

### Screenshots

image

### PR DESCRIPTION
**Pull request by Adhetya**
## 🛠️ Fixes Issue

Closes #267 

## 👨‍💻 Changes proposed
Made changes to counselling page

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Before changes:
Screenshot 2022-04-20 at 11 54 24 AM

After changes:
Screenshot 2022-04-20 at 11 52 51 AM

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
Hey @Adhetya I have not asked you to change the UI of this page .I asked you to make a separate page for the counselling ,that's why the issue is labeled as Level 3 .

**Comment by Adhetya** [comment]
Oh okay. Does this mean I should remove this section in the main page?

**Comment by The-Shivam-garg** [comment]
No this means .
Make a seprate page on which we get directed by clicking on Get counselling
button from the home page

**Comment by Adhetya** [comment]
@The-Shivam-garg, I have created the counselling page. You can check it out now

**Pull request closed without merging**
