### PR TITLE
New background image in the Feedback section 

### LINKED ISSUE #134: Enhancement: Add a Background image in the Feedback section
bigb3

### PR DESCRIPTION
**Pull request by Rishita489**
## 🛠️ Fixes Issue #134 

Closes #134 

## 👨‍💻 Changes proposed

I have added an improved quality background image in the feedback section . 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

image

### CODE REVIEW

**Review by sakshamgurbhele — APPROVED** [review]
LGTM

**Comment by sakshamgurbhele** [comment]
@Rishita489 Well done, Merging it 🚀

**Comment by sakshamgurbhele** [comment]
@Rishita489 I have reverted your PR, It is causing conflicts with existing PRs. I recommend you to open a single PR for a single Issue, Thankyou.

**Comment by sakshamgurbhele** [comment]
Go ahead and open a new PR for Background Image, I have reopened the Background issue for you #134

**Comment by Rishita489** [comment]
Hey @sakshamgurbhele , you can revert back my PR #280 and commit PR #286 .

**Comment by sakshamgurbhele** [comment]
> Hey @sakshamgurbhele , you can revert back my PR #280 and commit PR #286 .

It's already reverted 3 hours back 
ref #290

**Pull request merged**
