### PR TITLE
Enhanced Button and Improved Effect on Image 

### LINKED ISSUE #239: [FEATURE] Fix "Gain new skills" banner and correct alignment
### Description

Screenshot 2022-04-03 at 11 25 56 PM

the effect on image doesn't look good, maybe you can try new effects. 
button can be enhanced (may be you can try to match the color scheme, or maybe you can add some effects to it, or maybe alignment and many more can be done. 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Anjuli08**
## 🛠️ Fixes Issue

Closes #239 

## 👨‍💻 Changes proposed
Improved color of button and hover effect
Highlighted Join NOW
Modified effect on Image

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
ss

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
Please resolve your PR conflicts

**Comment by Anjuli08** [comment]
done

**Comment by The-Shivam-garg** [comment]
Hey @Anjuli08 the code has so many bugs yet , please resolve them and make a separate PR for this issue .For Example:

image
image
image

**Comment by Anjuli08** [comment]
> Hey @Anjuli08 the code has so many bugs yet , please resolve them and make a separate PR for this issue .For Example:
> 
> image image image

Hello sir, I have updated the file and tried to remove these bugs. please review it and let me know if any left

**Comment by The-Shivam-garg** [comment]
Hey @Anjuli08 there are so many bugs now in your update

**Pull request closed without merging**
