### PR TITLE
dark mode final

### PR DESCRIPTION
**Pull request by SSaurabhsahuu**
added dark mode to all pages except blog page

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
hey, deploy the website and share the link so that i can check out  the working of your feature

**Comment by SSaurabhsahuu** [comment]
check this link  https://frosty-golick-d42220.netlify.app/index.html

**Comment by The-Shivam-garg** [comment]
Thank you @SSaurabhsahuu for resolving the issue, I have merged your code

**Comment by SSaurabhsahuu** [comment]
😀😁

**Pull request merged**
