### PR TITLE
Changed the testimonial texts, names and images.

### LINKED ISSUE #263: [FEATURE] Change the TESTIMONIAL TEXT to something meaning full, and try to maintain a similar flow for format and content size.
### Description

Change the TESTIMONIAL TEXT to something meaning full, and try to maintain a similar flow for format and content size.

### Screenshots

image

### PR DESCRIPTION
**Pull request by Pranai2518**
## 🛠️ Fixes Issue

Closes #263 

## 👨‍💻 Changes proposed

Changed the text, names and images.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by sakshamgurbhele — CHANGES_REQUESTED** [review]
Screenshot 2022-04-08 at 4 51 18 PM
content looks genuine, good work @pranai251.
can you please change the names and display pictures also!?

**Comment by Pranai2518** [comment]
Yeah Sure! I'll do that @sakshamgurbhele.

**Comment by Pranai2518** [comment]
Hey @sakshamgurbhele. I have updated with the requested changes. You can review it.

**Comment by Pranai2518** [comment]
Hey @sakshamgurbhele. Kindly review this PR.

**Comment by sakshamgurbhele** [comment]
Screenshot 2022-04-17 at 7 40 57 PM
@Pranai2518 Look into this,

**Comment by Pranai2518** [comment]
Hey @sakshamgurbhele. I have resolved it. Kindly review and merge the PR.

**Comment by The-Shivam-garg** [comment]
Great! @Pranai2518 Your code is merged

**Pull request merged**
