### PR TITLE
Fixed the blog page sidebar issue.

### PR DESCRIPTION
**Pull request by DarkFalc0n**
#62 Resolved the CSS/HTML bugs that resulted in incorrect sidebar display.

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
please resolve the or conflicts

**Comment by The-Shivam-garg** [comment]
please resolve your pr conflicts

**Comment by DarkFalc0n** [comment]
> please resolve your pr conflicts

I resolved the conflicts

**Comment by The-Shivam-garg** [comment]
great ! @DarkFalc0n thank you on working this issue, I have merged your code.

**Pull request merged**
