### PR TITLE
Fixes Issue #136

### PR DESCRIPTION
**Pull request by BabyElias**
Fixes Issue #136

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
can you please deploy the website, through github pages and share the link for the same

**Comment by BabyElias** [comment]
Ok Sure.

**Comment by BabyElias** [comment]
I will be creating a new PR resolving issue #160 as upon seeing the page with previously made changes,I made another color change pertaining to my issue.

**Comment by BabyElias** [comment]
I changed the text color to white again.

Link to site : https://babyelias.github.io/BigB-E-learn-Websit-e/
Also attaching the change I made.
sss

**Comment by The-Shivam-garg** [comment]
cool ! @BabyElias your code is merged

**Pull request merged**
