### PR TITLE
#68 Updated navbar

### PR DESCRIPTION
**Pull request by Srijita-Mandal**
Issue #68 
Fixed the navbar of the pages top.
Linked all pages properly.
preview: https://srijita-mandal.github.io/BigB-E-learn-Websit-e/Blog/blog.html

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
image
please go through this @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
> image please go through this @Srijita-Mandal

Oh yes. Actually it 

> image please go through this @Srijita-Mandal

Oh sure.. I'll check it.

**Comment by Srijita-Mandal** [comment]
> image please go through this @Srijita-Mandal

Oh sure.. I'll check it

**Comment by Srijita-Mandal** [comment]
@The-Shivam-garg Can you please give me one more day.. I'll definitely fix the issue. I was sick from last two days actually.

**Comment by Srijita-Mandal** [comment]
Please check it.

**Comment by The-Shivam-garg** [comment]
image

hey @Srijita-Mandal  keep the navbar in full length , It will be much better

**Comment by Srijita-Mandal** [comment]
I made it width 100% and tried multiple ways to make full length, but ultimately it becomes like this. May be it's for many defined classes of the page. I couldn't make it, sorry.

**Comment by The-Shivam-garg** [comment]
no issue @Srijita-Mandal , you can start working on other issues. But as the code is not ,what is expected .I cant merge it

**Pull request closed without merging**
