### PR TITLE
Fixed Issue 116

### LINKED ISSUE #116: Enhancement : Expanding Underlined text animation on hover
### Description

- I want to add underlined text animation on hover for this website.

### Screenshot

- Please assign me on this issue this under GSSOC '22.

Image

### PR DESCRIPTION
**Pull request by TG922**
## 🛠️ Fixes Issue

Closes #116

## 👨‍💻 Changes proposed

- Removed Static Text with Link
- Added underlined text animation on hover for this website.

## ✔️ Check List (Check all the applicable boxes) 

- [x] - Correct; marked as done
- [] - Not correct; marked as **not** done

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Image21

### CODE REVIEW

**Comment by sakshamgurbhele** [comment]
@TG922 Make sure you do the alignment to all the heading so that they look decent/.

**Comment by TG922** [comment]
Ok I will do it today I was having exam

**Comment by TG922** [comment]
OK I'm on it will send PR within some hour

**Comment by TG922** [comment]
@sakshamgurbhele can u assign #117, #215 I have already worked on it just require to send PR for that.

I accept I took more time for this project to solve the issue than was expected !! I was having internal and external both that took more time in March.

**Pull request closed without merging**
