### PR TITLE
Add more relevant courses in the Course page 

### PR DESCRIPTION
**Pull request by Mohit-1909**
#3 Added Data science and Database Management System courses

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
hey @Mohit-1909 can you please deploy it with the github pages so i can have a look to its output

**Comment by Mohit-1909** [comment]
Screenshot (103)
Screenshot (102)
Screenshot (101)
Screenshot (100)
Screenshot (99)
Screenshot (98)

**Comment by The-Shivam-garg** [comment]
cool ! @Mohit-1909 I have merged your code.

**Comment by Mohit-1909** [comment]
Thank you!!

**Pull request merged**
