### PR TITLE
updated UI for blog page

### LINKED ISSUE #7: Improve the UI of the Blogs Section
**Feature description**

👀 Have you spent some time to check if this issue has been raised before?

- [ ]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?

- [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by whiteHatpro**
fixes #7

### CODE REVIEW

**Comment by whiteHatpro** [comment]
@The-Shivam-garg please review it

**Comment by The-Shivam-garg** [comment]
please share the screenshot of the ui that you fixed

**Comment by whiteHatpro** [comment]
1) increased the size of the logo so that it can be visible more clearly in all views
screenshot-127 0 0 1_5501-2022 02 04-12_36_11

2)customised the text to be more adaptable to the background
screenshot-127 0 0 1_5501-2022 02 04-12_36_24

3)maked the category more bold so that it can be easily readable and distinguished from the numbers
screenshot-127 0 0 1_5501-2022 02 04-12_36_39

4)customised the whole footer to give it a better look
screenshot-127 0 0 1_5501-2022 02 04-12_37_03

**Comment by The-Shivam-garg** [comment]
Thanks @whiteHatpro for resolving the issue. I will merge your code.

**Pull request merged**
