### PR TITLE
Event Page created

### LINKED ISSUE #123: Feature: Create a separate new page for Events
There is a link of event in footer, so I can create an link the event page.

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
Event Page Created

## 🛠️ Fixes Issue

Closes #123 

## 👨‍💻 Changes proposed
- I have created a new event page
- It has the list of all hackathons(dummy)
- It also has a cool new banner

## ✔️ Check List (Check all the applicable boxes) 
[x] I have maintained the same style of navigation bar
[x] I have maintained the same style of footer design
[ ] Not too much responsiveness like index.html
[ ] Includes all links of navigation bar

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
If possible you can add more responsiveness and dummy events to website to make it look more cool.

## 📷 Screenshots
image
image
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
Bro some one's pull request messed up the website

**Comment by Kumar-laxmi** [comment]
Like right now I have cloned the website and website itself has conflicts

**Comment by Kumar-laxmi** [comment]
The program has been double written in index.html

**Comment by The-Shivam-garg** [comment]
Thanks for informing me, the issue is resolved now

**Comment by Kumar-laxmi** [comment]
I have created a new pull request

**Pull request closed without merging**
