### PR TITLE
solved #137

### PR DESCRIPTION
**Pull request by the-centinal**
features and blog page have their own interactive footer so its ok not to change them.

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
can you please explain then, what changes did you made ?

**Comment by the-centinal** [comment]
sir i changed footer of courses and contact us page

**Comment by The-Shivam-garg** [comment]
please resolve your PR conflicts @the-centinal

**Comment by the-centinal** [comment]
i've solved the conflicts sir

**Comment by The-Shivam-garg** [comment]
Still pr have the conflicts

**Comment by sakshamgurbhele** [comment]
@the-centinal Kindly resolve the Conflicts, so that we can merge.

**Comment by sakshamgurbhele** [comment]
https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/issues/137

**Review by sakshamgurbhele — APPROVED** [review]

**Review by sakshamgurbhele — APPROVED** [review]

**Review by sakshamgurbhele — APPROVED** [review]
LGTM 👍🏼

**Comment by sakshamgurbhele** [comment]
@the-centinal ThankYou for contributing, Merging it 🚀

**Pull request merged**
