### PR TITLE
Changed the static counter to animated counter

### PR DESCRIPTION
**Pull request by Abhilasha-Jairath**
Added animated counter

## 🛠️ Fixes Issue #112 

Closes #

## 👨‍💻 Changes proposed

changed the static counter to animated ounter

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot 2022-04-06 024925

### CODE REVIEW

**Comment by Abhilasha-Jairath** [comment]
Added animated counter

**Comment by The-Shivam-garg** [comment]
image
It is not showing the desired output as you mentioned in the PR , apart from this your PR has a conflicts . @Abhilasha-Jairath

**Comment by ronitrangwani** [comment]
> image It is not showing the desired output as you mentioned in the PR , apart from this your PR has a conflicts . @Abhilasha-Jairath

I'll update the complete folder today. Kindly recheck once

**Comment by Abhilasha-Jairath** [comment]
Corrected the animated counter files , Please check it

**Pull request closed without merging**
