### PR TITLE
Real Time Updation #27

### PR DESCRIPTION
**Pull request by barnik109**
Issue done.

### CODE REVIEW

**Comment by barnik109** [comment]
Okk will do.

**Comment by barnik109** [comment]
https://barnik109.github.io/BigB-E-learn-Websit-e/

**Comment by The-Shivam-garg** [comment]
Fine i will merge it tomorrow.

**Comment by barnik109** [comment]
Yeah okay thanks.

**Comment by The-Shivam-garg** [comment]
great @barnik109 . Thanks for resolving out the issue, I have merged your code.

**Pull request merged**
