### PR TITLE
Font size and night mode button position fixed.

### LINKED ISSUE #310: Bringing the night mode button at proper position in courses page.
### Description

The Night Mode button inside the [Courses](url) page is not at the right position.
I will bring it at the top right corner of the page.

I am contributor at GSSOC'22.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Siddhesh777**
## 🛠️ Fixes Issue

Closes #310

## 👨‍💻 Changes proposed
  Position of night-mode button adjusted.
  font size adjusted.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
Hey @Siddhesh777 do the required changes , as per the requirement don't spoil other code ,As in this I think you have change the image length of card due to which they got suppress , please make sure everything is ohk before you create a pull request

**Comment by Siddhesh777** [comment]
Hey @The-Shivam-garg 
Everything ok?
Or any modifications is needed?

**Comment by Siddhesh777** [comment]
Ok @The-Shivam-garg 
I will do it soon

**Comment by Siddhesh777** [comment]
hey @The-Shivam-garg I have made the changes.

**Pull request closed without merging**
