### PR TITLE
fixed dark mode buton and explore section's links

### PR DESCRIPTION
**Pull request by codingkush**
fixed the dark mode button position and links of explore section in course page ..

now every links are working properly in explore section of course page

## 📷 Screenshots

DARK  MODE BUTTON position 

dars

EXPLORE SECTION'S LINK 

explore

NOW ,you can see that feautre link of explore section are working properly and opening....and other links are also working properly..

feature

### CODE REVIEW

**Comment by The-Shivam-garg** [comment]
hey @codingkush the position won't seems that good , please find a suitable position for the toggle

**Comment by codingkush** [comment]
Ok ...

**Comment by codingkush** [comment]
Sir ....is this position looks good ??

Screenshot :- 
dkm

hjk

**Comment by sakshamgurbhele** [comment]
@codingkush Quite Bearable, Can you put this along with the "SIGN IN" button!? 
also, freeze it so that the user can toggle between dark mode and light mode from anywhere on the page.

**Review by sakshamgurbhele — CHANGES_REQUESTED** [review]
work on position of toggle

**Comment by codingkush** [comment]
Yes ...

**Comment by codingkush** [comment]
pls tell me ...is this ok??

opw

opd

**Comment by codingkush** [comment]
Sir...is this ok?

**Comment by sakshamgurbhele** [comment]
> Sir...is this ok?

Looks good

**Comment by codingkush** [comment]
i have done what you wanted ...

opd

opw

**Review by sakshamgurbhele — APPROVED** [review]
LGTM, Good Work @codingkush. Merging it 🚀

**Pull request merged**
