### PR TITLE
Feature Page synced to Project theme

### LINKED ISSUE #283: Feature Page syncing to repo design
### Description

In the feature page we can see that the this page isn't matching the  header and footer design like other pages, so I can sync it like other pages

### Screenshots

image

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
## 🛠️ Fixes Issue

Closes #283 

## 👨‍💻 Changes proposed
- Change the header and footer in Feature Page

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Nothing

## 📷 Screenshots
image
image

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@sakshamgurbhele @The-Shivam-garg Pls review my PR

**Comment by sakshamgurbhele** [comment]
@Kumar-laxmi I didn't find this attractive enough to merge into master code, maybe you can try something else and then will look into if I can merge it. ThankYou.

**Comment by sakshamgurbhele** [comment]
> @Kumar-laxmi I didn't find this attractive enough to merge into master code, maybe you can try something else and then will look into if I can merge it. ThankYou.

Contributions are always Appreciated!

**Comment by Kumar-laxmi** [comment]
@sakshamgurbhele Please suggest what I can do more to make it better

**Pull request closed without merging**
